name: Go Format
on:
  pull_request:
    paths:
      - "**/*.go"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Format golang files
        run: git ls-files | grep ".go$" | xargs gofmt -s -w -l
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes for go files
          branch: ${{ github.head_ref }}